//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cross.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cross.Exceptions.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accion no Autorizada para el Tipo de Usuario..
        /// </summary>
        public static string AccionNoAutorizadaParaElUsuario {
            get {
                return ResourceManager.GetString("AccionNoAutorizadaParaElUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe ser un número..
        /// </summary>
        public static string ElCampoXDebeSerNumerico {
            get {
                return ResourceManager.GetString("ElCampoXDebeSerNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es requerido..
        /// </summary>
        public static string ElCampoXEsRequerido {
            get {
                return ResourceManager.GetString("ElCampoXEsRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Fecha de Nacimiento no puede ser mayor o igual a la Fecha de Hoy..
        /// </summary>
        public static string LaFechaDeNacimientoNoPuedeSerMayorOIgualALaFechaDeHoy {
            get {
                return ResourceManager.GetString("LaFechaDeNacimientoNoPuedeSerMayorOIgualALaFechaDeHoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Materia y la Comision seleccionadas no pertenecen al mismo Plan: {0}..
        /// </summary>
        public static string LaMateriaYLaComisionNoPertenecenAlMismoPlanX {
            get {
                return ResourceManager.GetString("LaMateriaYLaComisionNoPertenecenAlMismoPlanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden..
        /// </summary>
        public static string LasClavesNoCoinciden {
            get {
                return ResourceManager.GetString("LasClavesNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron Resultados..
        /// </summary>
        public static string SinResultados {
            get {
                return ResourceManager.GetString("SinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario y/o Contraseña incorrectos..
        /// </summary>
        public static string UsuarioOContraseniaIncorrectos {
            get {
                return ResourceManager.GetString("UsuarioOContraseniaIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una Persona registrada con Legajo: {0}..
        /// </summary>
        public static string YaExisteUnaPersonaRegistradaConLegajoX {
            get {
                return ResourceManager.GetString("YaExisteUnaPersonaRegistradaConLegajoX", resourceCulture);
            }
        }
    }
}
